name: LegacyCombat
version: 'Aplpha-0.1'
main: fr.cozyhouse.legacyCombat.LegacyCombat
api-version: '1.21'
commands:
  legacycombat:
    description: initial plugin command
    permission: legacycombat.admin
